# https://github.com/JohnnyMorganz/StyLua#options
#───────────────────────────────────────────────────────────────────────────────
syntax = "LuaJIT"  # needed to support `::labels::`
column_width = 100
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 3
quote_style = "AutoPreferDouble"
call_parentheses = "NoSingleTable"
collapse_simple_statement = "Always"
sort_requires.enabled = true
