name: nvim type check

on:
  push:
    branches: [main]
    paths: ["**.lua"]
  pull_request: 
    paths: ["**.lua"]

jobs:
  build:
    name: nvim type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: stevearc/nvim-typecheck-action@v2
