name: panvimdoc

on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/panvimdoc.yml
  workflow_dispatch: {} # allows manual execution

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  docs:
    runs-on: ubuntu-latest
    name: README.md to vimdoc
    steps:
      - uses: actions/checkout@v5
      - run: git pull # fix failure when multiple commits are pushed in succession
      - run: mkdir -p doc

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}
          version: "Neovim"
          demojify: true
          treesitter: true

      - run: git pull
      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: auto-generate vimdocs"
          branch: ${{ github.head_ref }}
